---
name: Release

"on":
  push:
    branches:
      - master

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  deploy-documentation:
    name: Deploy Documentation to GitHub Pages
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: "./yarn.lock"
      - name: Install dependencies
        run: yarn && yarn bootstrap
      - name: Build documentation
        run: yarn build:docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build
          user_name: QubitPi
          user_email: jack20191124@proton.me
